# Generated by Django 3.1 on 2020-08-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200812_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
